/**
 * The relay protocol's crypto, in pure JavaScript.
 *
 * Must produce byte-for-byte the same results as src/shared/relay.ts on the
 * desktop, which uses WebCrypto: SHA-256 for the key, device id and join
 * proof, and AES-256-GCM with a 12-byte nonce for every frame. crypto.test.ts
 * checks that against vectors generated by WebCrypto rather than assuming it.
 *
 * @noble rather than react-native-quick-crypto because that is a native module,
 * and a single native dependency makes the whole project unloadable in Expo Go.
 */
import { gcm } from '@noble/ciphers/aes.js'
import { sha256 } from '@noble/hashes/sha2.js'

export function toBase64Url(bytes: Uint8Array): string {
  let binary = ''
  for (let i = 0; i < bytes.length; i += 1) binary += String.fromCharCode(bytes[i])
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

export function fromBase64Url(value: string): Uint8Array {
  const base64 = value.replace(/-/g, '+').replace(/_/g, '/')
  const binary = atob(base64 + '='.repeat((4 - (base64.length % 4)) % 4))
  const out = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i)
  return out
}

function digest(input: string): Uint8Array {
  return sha256(new TextEncoder().encode(input))
}

/** The AES key both endpoints derive from the shared secret. */
export function deriveKey(secret: string): Uint8Array {
  return digest(`boss-relay-key:${secret}`)
}

/** Routing key. A separate derivation, so holding it does not yield the key. */
export function deriveDeviceId(secret: string): string {
  return toBase64Url(digest(`boss-relay-device:${secret}`).slice(0, 16))
}

/** Proves room membership to the relay without disclosing the secret. */
export function deriveJoinProof(secret: string): string {
  return toBase64Url(digest(`boss-relay-join:${secret}`).slice(0, 16))
}

/** `base64url(iv).base64url(ciphertext+tag)`, matching the desktop's format. */
export function seal(key: Uint8Array, message: unknown): string {
  const iv = crypto.getRandomValues(new Uint8Array(12))
  const sealed = gcm(key, iv).encrypt(new TextEncoder().encode(JSON.stringify(message)))
  return `${toBase64Url(iv)}.${toBase64Url(sealed)}`
}

/** Returns null for a wrong key, a truncated frame, or a failed tag check. */
export function open<T>(key: Uint8Array, sealed: string): T | null {
  const [ivPart, bodyPart] = sealed.split('.')
  if (!ivPart || !bodyPart) return null
  try {
    const plain = gcm(key, fromBase64Url(ivPart)).decrypt(fromBase64Url(bodyPart))
    return JSON.parse(new TextDecoder().decode(plain)) as T
  } catch {
    return null
  }
}
