import type { LabAssistantWorkflowConfig } from '../shared/lab-assistant'
import type { WorkflowBudget } from '../shared/workflow'

/**
 * Generates the durable-engine script for a Lab Assistant managed task:
 * plan → implement → review cycles, exactly the pipeline the bespoke
 * state machine in lab-assistant-manager used to drive off thread.result
 * events. As an engine script it gains what that machine never had —
 * journaled steps, restart-safe resumption mid-stage, and budgets.
 *
 * Task fields and the role configuration are baked in as literals, so the
 * script is fully deterministic and readable in the Workflows page.
 */

export interface TaskWorkflowInput {
  title: string
  details?: string
}

function literal(value: unknown): string {
  return JSON.stringify(value)
}

export function taskWorkflowBudget(config: LabAssistantWorkflowConfig): Partial<WorkflowBudget> {
  // Plan + implement + (reviewers + one revision) per cycle, with slack for
  // a judge or retry. The ceiling exists to stop runaway loops, not to be hit.
  return {
    maxAgentRuns: 2 + (config.reviewers.length + 1) * config.maxReviewCycles + 2,
    maxRunHours: 72
  }
}

export function taskWorkflowScript(task: TaskWorkflowInput, config: LabAssistantWorkflowConfig): string {
  const plannerPrompt = [
    '[Lab Assistant managed workflow — planner]',
    `Plan this task: ${task.title}.`,
    task.details ? `User context: ${task.details}` : '',
    'Inspect the project and produce a concrete implementation plan. Do not edit files.',
    'Call out risks, required tests, and anything that needs a user decision.',
    config.planner.instruction ?? ''
  ].filter(Boolean).join('\n\n')
  const implementerPrompt = [
    '[Lab Assistant managed workflow — implementer]',
    `Implement the planned task: ${task.title}.`,
    task.details ? `User context: ${task.details}` : '',
    'Work in the isolated Git worktree created for this thread. Follow the planner handoff, update tests with behavior, and verify the change as far as the environment permits.',
    config.implementer.instruction ?? ''
  ].filter(Boolean).join('\n\n')
  const reviewerPrompts = config.reviewers.map((reviewer) =>
    [
      '[Lab Assistant managed workflow — reviewer]',
      `Review the implementation of: ${task.title}.`,
      'Inspect the implementation checkout, tests, and the implementer handoff. Do not edit files.',
      'End your final response with exactly PASS or CHANGES_REQUESTED. For changes, put actionable bullet points after CHANGES_REQUESTED.',
      reviewer.instruction ?? ''
    ].filter(Boolean).join('\n\n')
  )
  const revisePrefix = [
    '[Lab Assistant managed workflow — review feedback]',
    `Review requested changes for ${task.title}. Address every point, update tests, and rerun relevant checks.`
  ].join('\n\n')

  return `// Managed task pipeline, generated by Lab Assistant.
const planner = ${literal(config.planner)}
const implementer = ${literal(config.implementer)}
const reviewers = ${literal(config.reviewers)}
const reviewerPrompts = ${literal(reviewerPrompts)}
const maxReviewCycles = ${literal(config.maxReviewCycles)}
const title = ${literal(task.title)}

function verdictOf(text) {
  const lines = String(text || '').trim().split('\\n').map((line) => line.trim())
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    if (/^PASS\\b/.test(lines[i])) return { verdict: 'pass', notes: [] }
    if (/^CHANGES_REQUESTED\\b/.test(lines[i])) return { verdict: 'changes', notes: lines.slice(i + 1).filter(Boolean) }
  }
  return null
}

const plan = await agent(${literal(plannerPrompt)}, {
  backendId: planner.backendId, model: planner.model, workspace: 'project', mode: 'plan', title: 'Plan · ' + title
})
if (plan.status !== 'success') throw new Error('Planner ended with ' + (plan.error || plan.status) + '.')

const impl = await agent(${literal(implementerPrompt)} + '\\n\\nPlanner handoff:\\n\\n' + (plan.text || plan.summary || ''), {
  backendId: implementer.backendId, model: implementer.model, workspace: 'worktree', mode: 'auto', title: 'Implement · ' + title
})
if (impl.status !== 'success') throw new Error('Implementer ended with ' + (impl.error || impl.status) + '.')

let cycle = 1
while (true) {
  let feedback = null
  for (let i = 0; i < reviewers.length; i += 1) {
    const review = await agent(reviewerPrompts[i], {
      backendId: reviewers[i].backendId, model: reviewers[i].model,
      inWorktreeOf: impl.threadId, mode: 'plan', title: 'Review ' + (i + 1) + ' · ' + title + ' · cycle ' + cycle
    })
    if (review.status !== 'success') throw new Error('Reviewer ' + (i + 1) + ' ended with ' + (review.error || review.status) + '.')
    const verdict = verdictOf(review.text)
    if (!verdict) throw new Error('Reviewer ' + (i + 1) + ' finished without PASS or CHANGES_REQUESTED.')
    if (verdict.verdict === 'changes') { feedback = verdict.notes; break }
    await log('Reviewer ' + (i + 1) + ' passed in cycle ' + cycle)
  }
  if (!feedback) break
  if (cycle >= maxReviewCycles) {
    throw new Error('Review still requests changes after ' + cycle + ' cycle' + (cycle === 1 ? '' : 's') + '.')
  }
  cycle += 1
  const notes = feedback.length ? feedback.map((note) => '- ' + note).join('\\n') : '- Re-read the reviewer transcript and address the requested changes.'
  const fix = await agent(${literal(revisePrefix)} + '\\n\\n' + notes, {
    backendId: implementer.backendId, model: implementer.model,
    inWorktreeOf: impl.threadId, mode: 'auto', title: 'Revise · ' + title + ' · cycle ' + cycle
  })
  if (fix.status !== 'success') throw new Error('Revision ended with ' + (fix.error || fix.status) + '.')
}
// Lab Assistant notifies task completion when it reconciles this run, so the
// script itself stays quiet on success.
return 'PASS in cycle ' + cycle
`
}
